encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.entry, name="entry"),
    path("create", views.create, name="create"),
    path("edit/<str:name>", views.edit, name="edit"),
    path("wiki/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
from django.shortcuts import render
import markdown2
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django import forms
from django.shortcuts import redirect
from django.urls import reverse

from . import util

class Search(forms.Form):
    item = forms.CharField()

class CreatePost(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(), label='')

class EditForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(), label='')
#creating search form

def index(request):
    entries = util.list_entries()
    searched = []
    if request.method == "POST":
        form = Search(request.POST)
        if form.is_valid():
            item = form.cleaned_data["item"]
            for i in entries:
                if item == i:
                    entry = f'/wiki/{item}'
                    return HttpResponseRedirect(entry)
                if item.lower() in i.lower():
                    searched.append(i)
            return render(request, "encyclopedia/search_result.html", {
            "form": Search(),
            "list": searched
            })
        else:
            return render(request, "encyclopedia/error.html", {
            "form": Search(),
            "message": "page not found"
            })
    else:
        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": Search()
    })

def entry(request, name):
    #calling list of entries
    entries = util.list_entries()
    #also the entry funtion passing in the name of the md file
    page = util.get_entry(name)
    #if name in entries then convert the md using markdown
    if name in entries:
        convert_page = markdown2.markdown(page)
        return render(request, "encyclopedia/entry.html", {
        "page": convert_page, "title": name.capitalize(),
        "form": Search()
        })
    else:
        return render(request, "encyclopedia/error.html", {
        "message": "No page found",
        "form": Search()
        })

def create(request):
    if request.method == 'POST':
        form = CreatePost(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            entries = util.list_entries()
            if title in entries:
                return render(request, "encyclopedia/error.html",{
                "message": "post already exists", "form": Search()
                })
            else:
                util.save_entry(title, content)
                newPost = util.get_entry(title)
                convert_page = markdown2.markdown(newPost)
                return render(request, "encyclopedia/entry.html", {
                "form": Search(),
                "message": "success",
                "page": convert_page })
    else:
        return render(request, "encyclopedia/create.html", {
        "form": Search(),
        "create": CreatePost()
        })

def edit(request, name):
    if request.method == 'GET':
        page = util.get_entry(name)
        return render(request, "encyclopedia/edit.html", {
        "form": Search(),
        "edit": EditForm(initial={'content':page})
        })
    else:
        form = EditForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(name, content)
            page = util.get_entry(name)
            convert_page = markdown2.markdown(page)
            return render(request, 'encyclopedia/entry.html', {
            "form": Search(),
            "title": name,
            "page": convert_page,
            "message": "success"
            })

def random_page(request):
    if request.method == 'GET':
        entries = util.list_entries()
        num = random.randint(0, len(entries) -1)
        random_p = entries[num]
        page = util.get_entry(random_p)
        convert_page = markdown2.markdown(page)
        return render(request, 'encyclopedia/entry.html', {
        "form":Search(),
        "title": random_p,
        "page": convert_page
        })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
{{ create }}
  <input type="submit" name="" value="submit">
</form>



{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  <h2 class="display-3">Edit: </h2>
  {{ edit }}
  <input type="submit" name="" value="save">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<div class="nav-link" style="width: 100px;">
<h6 style="background-color: green; color: white;">{{ message }}</h6>
</div>

<div style="border: 3px solid lightblue; padding: 20px; margin-right: 16px;">
    {{ page|safe }}
<a href=/edit/{{title}}>Edit Page</a>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>ERROR</h1>
{{ message }}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 class="display-4">All Pages</h1>
{{ message }}
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 class="display-2">Wiki</h2>
                <form class="" method="post" action="{% url 'encyclopedia:index' %}">
                {% csrf_token %}
                    <h6>Search: {{ form }}</h6>
                  </form>
                <div>
                    <a class="nav-link" href="/">Home</a>
                </div>
                <div>
                    <a class="nav-link" href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a class="nav-link" href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_result.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    {% for item in list %}
        <h2 class="display-4">Did You Mean:</h2>
        <hr>
        <li><a href=/wiki/{{item}}>{{ item }}</a></li>
        {% empty %}
            <h3>No item</h3>
    {% endfor %}
{% endblock %}